"""Publish lesson, source ledger and registry without altering existing lesson content."""
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1]
def write(path,data): (R/path).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
sources=[dict(id='gtsio-reviewed',tier=3,title='Continental GTSIO-520 reviewed overhaul manual, H difference data',path='C:/Users/user/KeonGeraldo/CodeProjects/DigiMan/work/deliverables/gtsio520/GTSIO520_full_reviewed.pdf',applicability='H section C-3-1 (PDF 151) applies basic procedures except stated differences; H fuel/induction fully replaced by C-3. Historical manual, not current service authority.'),dict(id='faa-powerplant',tier=1,title='FAA-H-8083-32B (2023), Powerplant',path='../Notes/amt_powerplant_handbook 2023.pdf',applicability='General teaching principles; no configuration dimensions or H-specific values.')]
steps=[]
def text(title,prompt,note,refs=('gtsio-reviewed',),**extra):steps.append(dict(type='text',title=title,prompt=prompt,note=note,sourceRefs=list(refs),**extra))
def pose(title,prompt,note,motion='Operating mechanism',progress=0,focus=None):
    s=dict(type='model-pose',title=title,prompt=prompt,note=note,sourceRefs=['gtsio-reviewed','faa-powerplant'],modelId='accessory-drives',savedMotionId=motion,motionProgress=progress)
    if focus:s['focusParts']=focus
    steps.append(s)
text('Where power goes','A turning crankshaft must supply ignition, lubrication, fuel delivery and aircraft equipment. Predict which devices need shaft power, and which device must put power into the engine before it can run.','FAA PDF p. 28, printed 1-7: accessory case, mounting pads and geared shafts. Lesson 8 follows the final 18-lesson curriculum; the older Day 8 plan is a practical/review day, not this lesson number.',('faa-powerplant',))
pose('Identify the section','Rotate the assembled study. Select the housing, crank gear, cam gear and idler. Open Inside and move a section plane through the chamber; distinguish solid wall from empty cavity.','FAA 1-7; GTSIO A-3-2 and A-4-8 (PDF 17,25). All dimensions, housing outline and inspection cover are illustrative. This is a subsystem study, not the full engine.')
pose('Expose interfaces','Scrub from assembled to exploded. Pause at any stage, rotate and select a seal, shaft, pad and coupling. Explain which part carries torque and which contains oil or locates the accessory.','GTSIO A-4-11 (PDF 28), A-4-15 (32), A-4-16 (33). Separation order and distances teach relationships; they are not maintenance instructions.','Exploded overview',100)
pose('Trace magneto power','Choose Magnetos under Trace power path, then isolate the complete path. Follow crank → idler → both drive gears → splined shafts → magnetos. Predict the idler direction before playing.','A-3-2; A-4-8; H C-3-2 (PDF 152): both magneto drives 1.5:1, CW facing engine drive pad. The mesh tooth counts are illustrative; the 1.5 output ratio is verified.','Focus: magnetos',25)
steps.append(dict(type='image',title='Mechanical to ignition',prompt='Follow each magneto to the upper and lower spark plugs. Explain how shaft rotation becomes timed spark energy and why the engine has two separate magnetos and two plugs per cylinder.',url='./lesson-media/gtsio-dual-ignition.webp',alt='Manufacturer GTSIO-520 dual ignition wiring figure',credit='Continental GTSIO-520 Figure A4-43; existing course extract',license='Course reference extract',note='FAA PDF 160-162 (4-1 to 4-3): magnet, primary and secondary circuits. H C-3-2 lists two magnetos and twelve plugs. This is two magnetos, not a single dual-magneto housing.',sourceRefs=['gtsio-reviewed','faa-powerplant']))
text('Timing and viewpoint','The H table gives 20° BTC for both magnetos. A drive speed ratio alone does not set ignition timing. Explain why a drive described as clockwise will appear counterclockwise when you view it from the opposite end.','H C-3-2 to C-3-3 (PDF 152-153). Accessory CW/CCW is facing the engine drive pad. Propeller CW is looking forward, with 0.667:1 propeller/crank ratio; do not use propeller RPM as crank RPM. No timing adjustment procedure is prescribed.')
pose('Fuel delivery','Select the Fuel path. Find the cluster gear, pump drive gear and detachable coupling. Scrub the focused motion. Explain how loss of torque at the coupling could interrupt engine-driven fuel delivery.','A-3-2; H C-3-6 (PDF 156): later pump replacement needs a changed drive gear and coupling; older installation differs. Fuel-drive ratio and rotation are unverified here; tooth sizes and motion are illustrative. Fuel pump internals are omitted. FAA PDF 84 (2-2) explains reciprocating fuel delivery.','Focus: fuel',50)
pose('Oil and speed indication','Trace the Oil and tachometer path. Section the pump housing and find the empty gear pockets. Identify the shaft that takes power from the camshaft and the separately represented tach output.','A-3-2; A-4-16; H C-3-2: tach output 0.5:1 CW. The relocated output represents an omitted bevel transfer. Pump gear sizes are illustrative. Figure A-4-8 items 10/11 are scavenge gears, not interchangeable tach labels. The existing IO-520 permold pump is a separate comparison study.','Focus: oil-tach',50)
pose('Electrical supply','Select Alternator and explain the conversion from shaft power to aircraft electrical supply. Compare the marked remote endpoint with the documented shaft train.','H C-3-3: 3:1 CW. A-4-13 identifies driven gear, hub and clutch spring; only its envelope and output are modelled here. The basic narrative mentions a generator pulley; its transfer geometry is not used as an H alternator claim. Dashed path is conceptual; transfer geometry remains unresolved.','Focus: alternator',50)
pose('Optional aircraft loads','Select the Vacuum path. Read the speed and viewpoint. Explain why a listed drive pad does not prove that a particular aircraft has the pump or that vacuum powers every aircraft instrument.','A-3-2 describes optional upper-rear accessories through magneto gear splines. H C-3-3 lists vacuum, deice and autopilot drives at 1.14:1 CCW. Useful pneumatic function and equipment are installation dependent; exact adapter transfer geometry and accessory internals are omitted.','Focus: vacuum',50)
pose('Governor remote drive','Select Governor. Trace crank → camshaft → front bevel drive → governor. Explain how mechanical speed sensing and oil control can change propeller blade angle.','A-3-2 documents the front camshaft bevel pair. H C-3-3: 0.809:1 CW. Governor is a front remote output, relocated into this study; bevel shapes omitted. FAA PDF 27 and 294 explain blade-angle/speed and oil-control functions.','Focus: governor',50)
pose('Starting reverses power','Before playing, predict the torque direction. Run Starter engagement and start. Pause during cranking, at engine takeover, and afterwards. Identify the worm, worm wheel, spring, drum and shaftgear.','A-3-2; A-4-15; FAA PDF 236 (5-6): spring tightens around drum during starting and releases after start. H starter drive 32:1 CCW facing pad applies during cranking. Clutch tightening, transition time and speed ramp are illustrative. No sliding Bendix pinion is added.','Starter engagement and start',10)
pose('Engine takes over','Scrub past the engine-takeover stage. Observe that worm drive and worm wheel stop while the shaftgear continues to turn with the crank gear. Explain why the clutch must separate these functions.','A-3-2 supports clutch release and continued crank-driven shaftgear. Model times and motor stop are a staged illustration, not measured dynamics or an aircraft starting checklist.','Starter engagement and start',80)
pose('Reassemble relationships','Reverse the exploded view. Pause halfway, isolate a complete path and inspect its seal and mounting interface. Return to assembled, then switch to normal operation and explain what must transmit torque.','Manufacturer exploded figures support part relationships. This staged reassembly is pedagogical; fastener torques, clearances, service limits and actual maintenance sequence are not represented.','Reassembly overview',50)
text('Illustrative faults','Discuss three hypothetical faults: (1) the fuel coupling transmits no torque, (2) the starter spring remains gripping after engine takeover, (3) a mounting seal leaks. For each, identify the first affected mechanical connection, its useful function and evidence needed before diagnosing the real engine.','ILLUSTRATIVE FAULT SCENARIOS: hypothetical reasoning from A-3-2, A-4-11, A-4-15 and C-3-6; no measured wear, pressure, seizure, failure probability or approved troubleshooting procedure is simulated.')
text('Explain the complete path','Choose an accessory and give a short explanation: source of energy → gears → shaft/coupling → interface → useful function. State one verified ratio, its viewpoint and one model limitation. Complete the knowledge checks.','Verified endpoints are in H C-3-2/C-3-3. Unresolved fuel ratio and optional transfer geometry must remain unknown. This assembly does not borrow IO-520 permold configuration.')
checks=[]
def mc(id,q,answers,correct,reason):checks.append(dict(id='accessory-'+id,lessonId='accessories-and-drives',type='multiple-choice',question=q,answers=answers,correct=correct,rationale=reason,sourceRefs=['gtsio-reviewed','faa-powerplant']))
mc('mag-path','Which path drives the GTSIO-520 magnetos?',['Crank gear → idler → magneto gears','Cam cluster → fuel coupling → magnetos','Propeller flange → starter motor'],0,'A-3-2 and A-4-8: crank gear drives idler, which drives both magneto gears.')
mc('ratio','At 1000 crank RPM, what is the H magneto drive speed?',['500 RPM','1000 RPM','1500 RPM'],2,'H C-3-2: 1.5 × 1000 = 1500 RPM. This is shaft drive speed, not a count of sparks.')
mc('view','The H accessory table states CW facing the engine drive pad. From the opposite end it appears:',['CW','CCW','Stopped'],1,'C-3-3 footnote defines the viewpoint. Apparent rotation reverses with viewpoint; the actual rotation has not changed.')
mc('unknown','Which value remains unverified in this study?',['H alternator 3:1','H tachometer 0.5:1','H fuel-pump drive ratio'],2,'C-3-2/C-3-3 verify alternator and tach ratios; no fuel-drive numerical value was established from the reviewed passages.')
checks.append(dict(id='accessory-start-path',lessonId='accessories-and-drives',type='ordering',question='Arrange the GTSIO starting torque path.',items=['Starter motor','Worm drive','Worm wheel','Clutch spring grips shaftgear drum','Shaftgear drives crankshaft gear'],rationale='A-3-2 and FAA 5-6 describe this torque path. The spring disengages after starting.',sourceRefs=['gtsio-reviewed','faa-powerplant']))
mc('takeover','After the engine starts, what does the manual say happens?',['Clutch spring releases; shaftgear remains engine-driven','Starter motor must continuously drive crankshaft','A sliding ring-gear pinion is proved by A-4-15'],0,'A-3-2 describes the spring returning and disengaging the starter; shaftgear then carries engine torque. This is a worm/spring adapter.')
mc('function','The governor mechanical drive supports which useful function?',['Propeller speed/blade-angle control using oil','Spark-plug voltage distribution','Fuel tank selection'],0,'FAA PDF 27,294: governor controls propeller speed and blade angle; H C-3-3 specifies its drive ratio.')
mc('evidence','Which statement accurately describes this 3D model?',['Manufacturer dimensions and exact pad positions','Documented relationships and endpoint ratios with illustrative solids','IO-520 permold parts automatically apply to GTSIO-520-H'],1,'H effectivity is established by C-3-1. Shapes, teeth, locations and travel are illustrative; the IO-520 pump is not used as GTSIO geometry.')
pack=dict(schema='4212.lesson-pack/v3',id='accessories-and-drives',title='Accessories & Drives',description='Lesson 8: trace GTSIO-520-H mechanical power into useful accessory functions.',privacy='Local progress only; no learner identity collected.',draftStatus='Source-backed teaching study — instructor and physical-phone review pending',sources=sources,lessons=[dict(id='accessories-and-drives',sequenceNumber=8,title='Accessories & Drives',objective='Identify accessories and interfaces, trace power paths, predict rotation, operate saved motions and explain useful functions and illustrative faults.',models=['accessory-drives'],listed=True,completionCriteria='Explain one full drive path, calculate a verified ratio with the correct viewpoint, inspect a section and distinguish evidence from illustration.',steps=steps)],checks=checks)
write('web/accessories-lessons.json',pack)
manifest=json.loads((R/'web/lessons-manifest.json').read_text(encoding='utf-8'));url='./accessories-lessons.json'
if url not in manifest['packs']:manifest['packs'].append(url)
write('web/lessons-manifest.json',manifest)
models=json.loads((R/'src/data/models.json').read_text(encoding='utf-8'))
if not any(m['id']=='accessory-drives' for m in models):
    models.append(dict(id='accessory-drives',label='GTSIO-520-H accessories and drives',adapter='animated-study',lessonControls=True,eyebrow='LESSON 8 / ACCESSORIES & DRIVES',description='Trace seven selectable power paths through a 47-part solid teaching assembly; operate, explode, reassemble and inspect the spring-clutch starting sequence. Dimensions are illustrative.',imageType='systems',badges=['47 components','10 saved motions','Verified H output ratios'],sources=[dict(localUrl='./accessory-drives.glb.gz',compressed=True)],contractUrl='./accessory-drives-contract.json'))
write('src/data/models.json',models)
asset_manifest=R/'docs/drive-asset-manifest.json'
if asset_manifest.exists():
    assets=json.loads(asset_manifest.read_text(encoding='utf8'))['web_assets']
    asset=next(a for a in assets if a['path']=='web/accessory-drives.glb.gz')
    if asset.get('drive_id'):
        next(m for m in models if m['id']=='accessory-drives')['sources'][0]['driveId']=asset['drive_id']
        write('src/data/models.json',models)
ledger=dict(engine_variant='GTSIO-520-H',date='2026-10-02',source_files=[],claims=[dict(id='effectivity',source='gtsio-reviewed',pdf_pages=[151],printed='C-3-1',claim='Basic GTSIO procedures apply except H differences; H fuel and induction fully covered in C-3.'),dict(id='topology',source='gtsio-reviewed',pdf_pages=[17,25],printed='A-3-2; A-4-8',claim='Crank→idler→magnetos; crank→cam cluster→fuel; cam spline→oil/tach; front cam bevel→governor; starter worm→wheel→clutch→shaftgear→crank.'),dict(id='ratios',source='gtsio-reviewed',pdf_pages=[152,153],printed='C-3-2/C-3-3',claim='Drive/crank: magnetos 1.5 CW; tach .5 CW; starter 32 CCW (cranking); alternator 3 CW; vacuum/deice/autopilot 1.14 CCW; governor .809 CW. All facing engine drive pad. Propeller .667 CW looking forward.'),dict(id='interfaces',source='gtsio-reviewed',pdf_pages=[28,30,32,33,156],printed='A-4-11/13/15/16; C-3-6',claim='Adapters, bushings, seals, gears, starter clutch and later H fuel coupling are identified.'),dict(id='general-functions',source='faa-powerplant',pdf_pages=[27,28,84,160,161,162,236,294],printed='1-6/7; 2-2; 4-1/3; 5-6; 7-8',claim='Accessory mounting and gearing; fuel delivery; magneto ignition; spring-clutch start; governor function.')],limitations=['All dimensions, tooth counts/profile, placements, seal details and explosion travel illustrative; no engineering fit or manufacture claim.','Cam 0.5 relationship follows four-stroke cycle; idler speed and fuel gearing chosen for schematic layout, not manufacturer tooth counts.','Governor front drive relocated; actual bevel transfer omitted. Vacuum adapter and H alternator intermediate geometry unresolved; dashed routes are conceptual.','Fuel ratio and fuel direction unverified. Tach ratio is not a separately verified oil-pump specification.','A-4-8 caption calls items 10/11 scavenge gears while narrative uses item 11 for tach; oil/tach naming cross-checked with A-4-16 rather than silently merging labels.','Basic A-3-2 generator pulley wording does not establish H gear-driven alternator transfer geometry.','No IO-520 configuration used; existing IO-520 permold pump remains a separate study.','No accessory detailed internals except referenced drive/clutch parts and schematic pump gear cavities. No flow, oil pressure, wear or failure dynamics.','Historical references do not establish current service applicability; no engine serial number or measured trainer supplied.','Native source solids and rebuild recipe are editable; not a constrained assembly or measured reverse-engineering model.'])
for source in sources:
    path=Path(source['path']) if source['id']=='gtsio-reviewed' else R/source['path']
    ledger['source_files'].append(dict(id=source['id'],path=str(path.resolve()),sha256=hashlib.sha256(path.read_bytes()).hexdigest()))
write('docs/accessory-reference-ledger.json',ledger)
print('Lesson 8 published:',len(steps),'steps;',len(checks),'checks')
