import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

const $=id=>document.getElementById(id), view=$('view');
const scene=new THREE.Scene();scene.background=new THREE.Color('#101923');
const camera=new THREE.PerspectiveCamera(38,1,.01,100);camera.position.set(1.45,1.05,1.8);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.localClippingEnabled=true;view.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xdceeff,0x34475b,2.8));for(const p of [[2,3,4],[-3,1,2]]){const l=new THREE.DirectionalLight(0xffffff,2.4);l.position.set(...p);scene.add(l)}
let mixer,action,clip,angle=0,playing=false,last=0,engineBox,engineContract;
const engineMeshes=[],clipPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
const objectLabel=o=>{const names=[];for(let node=o;node;node=node.parent)names.push(node.name||'');return names.join(' / ')};
function render(){controls.update();renderer.render(scene,camera)}
function setAngle(degrees){angle=(degrees%720+720)%720;if(mixer&&clip)mixer.setTime(clip.duration*angle/720);$('angle').value=String(angle);$('angle-value').textContent=`${angle.toFixed(0)}°`;const stroke=angle<180?'Power':angle<360?'Exhaust':angle<540?'Intake':'Compression';$('motion-state').textContent=`${stroke} stroke · native action sampled at ${angle.toFixed(0)}°.`;render()}
function tick(now){if(playing){setAngle(angle+Math.max(0,Math.min(.1,(now-last)/1000))*Number($('speed').value));last=now}requestAnimationFrame(tick)}
new ResizeObserver(()=>{const r=view.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render()}).observe(view);
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play';last=performance.now()};$('reset').onclick=()=>{playing=false;$('play').textContent='Play';setAngle(0)};$('angle').oninput=()=>{playing=false;$('play').textContent='Play';setAngle(Number($('angle').value))};
function groupMatches(label,id){const group=engineContract.inspection_groups.find(item=>item.id===id);if(!group) return false;if(group.selector.all)return true;return group.selector.any_regex.some(pattern=>new RegExp(pattern,'i').test(label));}
function applyGroup(){const mode=$('view-mode').value;for(const entry of engineMeshes)entry.mesh.visible=groupMatches(entry.label,mode);render()}
function isolateSearch(){const query=$('part-search').value.trim().toLowerCase();if(!query){applyGroup();return}let matches=0;for(const entry of engineMeshes){entry.mesh.visible=entry.label.toLowerCase().includes(query);if(entry.mesh.visible)matches++}$('status').textContent=matches?`Isolated ${matches} mesh${matches===1?'':'es'} matching “${query}”.`:`No exported mesh matches “${query}”.`;render()}
function applyCaseGhost(){const ghost=$('case-ghost').checked;for(const entry of engineMeshes)if(/V5 /i.test(entry.label))for(const material of entry.materials){material.transparent=ghost||material.userData.baseTransparent;material.opacity=ghost?.18:material.userData.baseOpacity;material.depthWrite=!ghost}render()}
function applySection(){const active=$('section-enabled').checked;$('section-controls').hidden=!active;const axis=$('section-axis').value;const normal=new THREE.Vector3(axis==='x'?1:0,axis==='y'?1:0,axis==='z'?1:0);const size=engineBox.getSize(new THREE.Vector3()),center=engineBox.getCenter(new THREE.Vector3());const extent=size[axis]/2;clipPlane.normal.copy(normal);clipPlane.constant=-(center[axis]+extent*Number($('section-position').value)/100);$('section-value').textContent=`${$('section-position').value}%`;for(const entry of engineMeshes)for(const material of entry.materials)material.clippingPlanes=active?[clipPlane]:null;render()}
$('view-mode').onchange=applyGroup;$('case-ghost').onchange=applyCaseGhost;$('section-enabled').onchange=applySection;$('section-axis').onchange=applySection;$('section-position').oninput=applySection;
$('isolate-search').onclick=isolateSearch;$('part-search').onkeydown=e=>{if(e.key==='Enter')isolateSearch()};$('show-all').onclick=()=>{$('part-search').value='';$('view-mode').value='all';$('case-ghost').checked=false;$('section-enabled').checked=false;applyGroup();applyCaseGhost();applySection()};
async function loadEngine(){try{const response=await fetch('./engine-contract.json');if(!response.ok)throw Error('Engine contract unavailable');engineContract=await response.json();if(engineContract.schema!=='4212.engine-contract/v1')throw Error('Unsupported engine contract');$('view-mode').replaceChildren(...engineContract.inspection_groups.map(group=>new Option(group.label,group.id)));new GLTFLoader().load(engineContract.asset.web_url,gltf=>{scene.add(gltf.scene);engineBox=new THREE.Box3().setFromObject(gltf.scene);const sphere=engineBox.getBoundingSphere(new THREE.Sphere());controls.target.copy(sphere.center);camera.position.copy(sphere.center).add(new THREE.Vector3(sphere.radius*1.35,sphere.radius*.8,sphere.radius*1.55));gltf.scene.traverse(mesh=>{if(!mesh.isMesh)return;const materials=(Array.isArray(mesh.material)?mesh.material:[mesh.material]).map(material=>{const copy=material.clone();copy.userData.baseOpacity=copy.opacity;copy.userData.baseTransparent=copy.transparent;return copy});mesh.material=Array.isArray(mesh.material)?materials:materials[0];engineMeshes.push({mesh,label:objectLabel(mesh),materials})});controls.update();const tracks=gltf.animations.flatMap(a=>a.tracks);if(!tracks.length)throw Error('Export contains no animation tracks');clip=new THREE.AnimationClip('720-degree engine motion',-1,tracks);mixer=new THREE.AnimationMixer(gltf.scene);action=mixer.clipAction(clip);action.paused=true;action.play();setAngle(0);for(const id of ['play','reset','angle','speed','view-mode','part-search','isolate-search','show-all','case-ghost','section-enabled'])$(id).disabled=false;$('status').textContent=`Loaded ${engineContract.id}: ${gltf.scene.children.length} root nodes, ${engineMeshes.length} selectable meshes and a ${clip.tracks.length}-track action.`;requestAnimationFrame(tick)},undefined,error=>{$('status').textContent='Could not load the exported engine: '+error.message;console.error(error)})}catch(error){$('status').textContent=error.message;console.error(error)}}
loadEngine();
